# This is a basic workflow to help you get started with Actions

name: CI - Deployment

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Hello, there!,
          echo Deploying is triggered.
      
      - name: SSH Deploy
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
            REMOTE_HOST: ${{ secrets.HOST }}
            REMOTE_USER: ${{ secrets.USERNAME }}
            SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
            ARGS: "-rltgoDzvO --delete"
            #SOURCE: "dist/"
            TARGET: ${{ secrets.TARGET_DIRECTORY }}

      - name: SSH Remote Commands
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.PRIVATE_KEY }}
            script_stop: true
            script: |
              echo "it's begining."
              whoami
              pwd
              echo "it's done"